steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crabywave/role-service:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/crabywave/role-service:$SHORT_SHA' ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/crabywave/role-service:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY